-- MySQL Script generated by MySQL Workbench
-- Thu Mar  1 10:15:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SCAIIF
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SCAIIF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SCAIIF` DEFAULT CHARACTER SET utf8 ;
USE `SCAIIF` ;

-- -----------------------------------------------------
-- Table `SCAIIF`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Actividad` (
  `noActividad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`noActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Alumno` (
  `matricula` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apPaterno` VARCHAR(45) NOT NULL,
  `apMaterno` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `lenguaIndigena` TINYINT NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Usuario` (
  `noPersonal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apPaterno` VARCHAR(45) NOT NULL,
  `apMaterno` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idCargo` INT NOT NULL,
  PRIMARY KEY (`noPersonal`),
  INDEX `fk_Usuario_Cargo_idx` (`idCargo` ASC),
  CONSTRAINT `fk_Usuario_Cargo`
    FOREIGN KEY (`idCargo`)
    REFERENCES `SCAIIF`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Aviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Aviso` (
  `noAviso` INT NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(45) NOT NULL,
  `mensaje` VARCHAR(45) NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  `fechaLimite` DATE NOT NULL,
  PRIMARY KEY (`noAviso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Curso` (
  `nrc` INT(5) NOT NULL,
  `nombreCurso` VARCHAR(45) NULL,
  `noCreditos` INT(2) NULL,
  `noPersonal` INT NOT NULL,
  PRIMARY KEY (`nrc`),
  INDEX `fk_Curso_Usuario1_idx` (`noPersonal` ASC),
  CONSTRAINT `fk_Curso_Usuario1`
    FOREIGN KEY (`noPersonal`)
    REFERENCES `SCAIIF`.`Usuario` (`noPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Modulo` (
  `idModulo` INT NOT NULL AUTO_INCREMENT,
  `noModulo` INT NOT NULL,
  PRIMARY KEY (`idModulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Seccion` (
  `idSeccion` INT NOT NULL AUTO_INCREMENT,
  `noSeccion` INT NOT NULL,
  PRIMARY KEY (`idSeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Conversacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Conversacion` (
  `idConversacion` INT NOT NULL AUTO_INCREMENT,
  `noConversacion` INT NOT NULL,
  PRIMARY KEY (`idConversacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`MaterialReportar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`MaterialReportar` (
  `noMaterial` INT NOT NULL AUTO_INCREMENT,
  `nombreMaterial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`noMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Calendario` (
  `idCalendario` INT NOT NULL AUTO_INCREMENT,
  `mes` VARCHAR(45) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `diaInicio` INT NOT NULL,
  `diaFin` INT NOT NULL,
  `diasFestivos` INT NOT NULL,
  `fechaLimiteExamen` DATE NOT NULL,
  `inicioVacaciones` DATE NOT NULL,
  `finVacaciones` DATE NOT NULL,
  `nrc` INT(5) NOT NULL,
  `idModulo` INT NOT NULL,
  `idSeccion` INT NOT NULL,
  `idConversacion` INT NOT NULL,
  `noMaterial` INT NOT NULL,
  PRIMARY KEY (`idCalendario`),
  INDEX `fk_Calendario_Curso1_idx` (`nrc` ASC),
  INDEX `fk_Calendario_Modulo1_idx` (`idModulo` ASC),
  INDEX `fk_Calendario_Seccion1_idx` (`idSeccion` ASC),
  INDEX `fk_Calendario_Conversacion1_idx` (`idConversacion` ASC),
  INDEX `fk_Calendario_MaterialReportar1_idx` (`noMaterial` ASC),
  CONSTRAINT `fk_Calendario_Curso1`
    FOREIGN KEY (`nrc`)
    REFERENCES `SCAIIF`.`Curso` (`nrc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_Modulo1`
    FOREIGN KEY (`idModulo`)
    REFERENCES `SCAIIF`.`Modulo` (`idModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_Seccion1`
    FOREIGN KEY (`idSeccion`)
    REFERENCES `SCAIIF`.`Seccion` (`idSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_Conversacion1`
    FOREIGN KEY (`idConversacion`)
    REFERENCES `SCAIIF`.`Conversacion` (`idConversacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_MaterialReportar1`
    FOREIGN KEY (`noMaterial`)
    REFERENCES `SCAIIF`.`MaterialReportar` (`noMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Reservacion` (
  `noActividad` INT NOT NULL,
  `matricula` INT NOT NULL,
  `noReservacion` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `asistencia` TINYINT NOT NULL,
  PRIMARY KEY (`noActividad`, `matricula`, `noReservacion`),
  INDEX `fk_Actividad_has_Alumno_Alumno1_idx` (`matricula` ASC),
  INDEX `fk_Actividad_has_Alumno_Actividad1_idx` (`noActividad` ASC),
  CONSTRAINT `fk_Actividad_has_Alumno_Actividad1`
    FOREIGN KEY (`noActividad`)
    REFERENCES `SCAIIF`.`Actividad` (`noActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_has_Alumno_Alumno1`
    FOREIGN KEY (`matricula`)
    REFERENCES `SCAIIF`.`Alumno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Observacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Observacion` (
  `matricula` VARCHAR(9) NOT NULL,
  `noPersonal` INT NOT NULL,
  `idObservacion` INT NOT NULL,
  `asunto` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`, `noPersonal`, `idObservacion`),
  INDEX `fk_Alumno_has_Usuario_Usuario1_idx` (`noPersonal` ASC),
  INDEX `fk_Alumno_has_Usuario_Alumno1_idx` (`matricula` ASC),
  CONSTRAINT `fk_Alumno_has_Usuario_Alumno1`
    FOREIGN KEY (`matricula`)
    REFERENCES `SCAIIF`.`Alumno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Usuario_Usuario1`
    FOREIGN KEY (`noPersonal`)
    REFERENCES `SCAIIF`.`Usuario` (`noPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCAIIF`.`Induccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCAIIF`.`Induccion` (
  `matricula` INT NOT NULL,
  `nrc` INT(5) NOT NULL,
  `idInduccion` INT NOT NULL,
  `cursoInduccion` TINYINT NOT NULL,
  `primeraAsesoria` TINYINT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`matricula`, `nrc`, `idInduccion`),
  INDEX `fk_Alumno_has_Curso_Curso1_idx` (`nrc` ASC),
  INDEX `fk_Alumno_has_Curso_Alumno1_idx` (`matricula` ASC),
  CONSTRAINT `fk_Alumno_has_Curso_Alumno1`
    FOREIGN KEY (`matricula`)
    REFERENCES `SCAIIF`.`Alumno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Curso_Curso1`
    FOREIGN KEY (`nrc`)
    REFERENCES `SCAIIF`.`Curso` (`nrc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
